"""Settings models and precedence resolution for Folionym entry points."""

from .models import (
    DATE_LOCALE_CHOICES,
    DESIRED_CASE_CHOICES,
    LANGUAGE_CHOICES,
    WORKFLOW_PRESET_CHOICES,
    ExtractionConfig,
    HeuristicCategoryConfig,
    HeuristicConfig,
    HeuristicScoreConfig,
    HeuristicSkipConfig,
    HeuristicWindowConfig,
    LLMBackendConfig,
    LLMConfig,
    LLMContentConfig,
    LLMRuntimeConfig,
    LLMVisionConfig,
    OutputConfig,
    OutputHookConfig,
    OutputModeConfig,
    OutputNamingConfig,
    OutputPathConfig,
    OutputProgressConfig,
    OutputTemplateConfig,
    OutputTraversalConfig,
    RenamerConfig,
    build_config_from_flat_dict,
)
from .resolution import build_config, preset_mode_values

__all__ = [
    "DATE_LOCALE_CHOICES",
    "DESIRED_CASE_CHOICES",
    "LANGUAGE_CHOICES",
    "WORKFLOW_PRESET_CHOICES",
    "ExtractionConfig",
    "HeuristicCategoryConfig",
    "HeuristicConfig",
    "HeuristicScoreConfig",
    "HeuristicSkipConfig",
    "HeuristicWindowConfig",
    "LLMBackendConfig",
    "LLMConfig",
    "LLMContentConfig",
    "LLMRuntimeConfig",
    "LLMVisionConfig",
    "OutputConfig",
    "OutputHookConfig",
    "OutputModeConfig",
    "OutputNamingConfig",
    "OutputPathConfig",
    "OutputProgressConfig",
    "OutputTemplateConfig",
    "OutputTraversalConfig",
    "RenamerConfig",
    "build_config",
    "build_config_from_flat_dict",
    "preset_mode_values",
]
